---
title: "meta-analysis study"
author: "Wu Yuqing,Zhou Yue,Zheng Yuxuan"
date: "6/18/2023"
format: html
execute:
  echo: fenced
---

# Summary of the original paper
Reference:Glass, G. V., & Smith, M. L. (1979). Meta-Analysis of Research on Class Size and Achievement. Educational Evaluation and Policy Analysis, 1(1), 2–16.
Published by: American Educational Research Association
Stable URL: <http://www.jstor.org/stable/1164099>

This paper is a research paper on the relationship between **class size** and **student achievement**. The researchers conducted a literature search to gather relevant studies on this topic. They found approximately 300 papers, but only 80 of them focused on the relationship between class size and achievement. This study examined the relationship between class size and academic achievement in schools. Previous research on this relationship has yielded mixed and inconsistent results. To address this issue, the research team collected data from nearly 80 studies, including more than 700 comparisons of achievement in small and large classes, involving nearly 900,000 students of various ages and subject areas. Through regression analysis of the data, the researchers found a significant inverse relationship between class size and academic achievement, indicating that larger class sizes are associated with lower academic achievement. In addition, the study found that reducing class size had the most significant impact on academic achievement when class size was reduced to less than 20 students.


*The project team encountered problems while further analyzing and reading the research paper. It was found that the paper did not provide any relevant code or datasets. This may be due to the age of the paper and the most complete dataset that could be found was printed out with unclear handwriting, making it difficult to read and organize. Considering the large amount of data and the limited time available, we would like to change the topic.*

